#!/data/data/com.termux/files/usr/bin/python

while True:
    print("Calculadora\n")
    print("1. Sumar")
    print("2. Restar")
    print("3. Multiplicar")
    print("4. Dividir")
    print("5. Salir\n")

    opcion = int(input("Selecciona una opción: "))

    if opcion == 5:
        break

    num1 = float(input("Ingresa el primer número: "))
    num2 = float(input("Ingresa el segundo número: "))

    if opcion == 1:
        resultado = num1 + num2
    elif opcion == 2:
        resultado = num1 - num2
    elif opcion == 3:
        resultado = num1 * num2
    elif opcion == 4:
        resultado = num1 / num2

    print("El resultado es:", resultado, "\n")

